### ISSUE TITLE
有bug 

### ISSUE THREAD

**Issue by tomy113** [rfyiamcool/go-timewheel#11]
package main

import (
	"fmt"
	"github.com/rfyiamcool/go-timewheel"
)
func main() {
	t1 := timewheel.NewTimer(time.Second * 1)
	t1.StopFunc(func() {
		fmt.Println("stop callback ",time.Now().String())
	})
	select {
	case <- t1.C:
		fmt.Println("done ",time.Now().String())
		t1.Stop()
	}

 }

输出结果 
done  2021-02-05 15:09:33.6385562 +0800 CST m=+2.023624201

但是 stop callback 没有输出

**Comment by tomy113** [comment]
应该在 timer.go 中的 435 行的 Stop 函数添加  如下逻辑 
 if t.fn != nil {
      t.fn()
}

**Comment by rfyiamcool** [comment]
已经解决, 谢谢

https://github.com/rfyiamcool/go-timewheel/commit/e51fd0f8b614c399ac20824e72aae20b84096cd5
