### ISSUE TITLE
TestAfterFuncResetStop 出错了

### ISSUE THREAD

**Issue by llxisdsh** [rfyiamcool/go-timewheel#12]
就是最近修改的结果,   如果 StopFunc表示仅仅Stop才会执行, 不如换个名字吧:)

func (t *Timer) StopFunc(callback func()) {
	t.stopFn = callback
}

**Comment by rfyiamcool** [comment]
提个pr吧。😁

**Comment by rfyiamcool** [comment]
已经修复 https://github.com/rfyiamcool/go-timewheel/pull/15
