### ISSUE TITLE
First delay will be longer

### ISSUE THREAD

**Issue by fufuok** [rfyiamcool/go-timewheel#28]
First of all, this library is great.

**v1.1.0**

```go
package main

import (
	"fmt"
	"time"

	"github.com/rfyiamcool/go-timewheel"
)

func main() {
	TW50ms, _ := timewheel.NewTimeWheel(50*time.Millisecond, 10)
	TW50ms.Start()
	defer TW50ms.Stop()

	now := time.Now()
	TW50ms.AfterFunc(100*time.Millisecond, func() {
		fmt.Println("cost(tick:50ms+after:100ms):", time.Since(now))
	})

	TW1s, _ := timewheel.NewTimeWheel(1*time.Second, 10)
	TW1s.Start()
	defer TW1s.Stop()

	now = time.Now()
	TW1s.AfterFunc(1*time.Second, func() {
		fmt.Println("cost(tick:1s+after:1s):", time.Since(now))
	})

	TW1s.Sleep(2 * time.Second)
}
```

```go
cost(tick:50ms+after:100ms): 150.0002ms
cost(tick:1s+after:1s): 2.0000005s
```

Ticker is the same, just first delay will be longer, and it would be better if there is no additional cost.

**Comment by fufuok** [comment]
Typos: https://github.com/rfyiamcool/go-timewheel#benchmark-test

**Comment by simonwu-os** [comment]
> First of all, this library is great.
> 
> **v1.1.0**
> 
> ```go
> package main
> 
> import (
> 	"fmt"
> 	"time"
> 
> 	"github.com/rfyiamcool/go-timewheel"
> )
> 
> func main() {
> 	TW50ms, _ := timewheel.NewTimeWheel(50*time.Millisecond, 10)
> 	TW50ms.Start()
> 	defer TW50ms.Stop()
> 
> 	now := time.Now()
> 	TW50ms.AfterFunc(100*time.Millisecond, func() {
> 		fmt.Println("cost(tick:50ms+after:100ms):", time.Since(now))
> 	})
> 
> 	TW1s, _ := timewheel.NewTimeWheel(1*time.Second, 10)
> 	TW1s.Start()
> 	defer TW1s.Stop()
> 
> 	now = time.Now()
> 	TW1s.AfterFunc(1*time.Second, func() {
> 		fmt.Println("cost(tick:1s+after:1s):", time.Since(now))
> 	})
> 
> 	TW1s.Sleep(2 * time.Second)
> }
> ```
> 
> ```go
> cost(tick:50ms+after:100ms): 150.0002ms
> cost(tick:1s+after:1s): 2.0000005s
> ```
> 
> Ticker is the same, just first delay will be longer, and it would be better if there is no additional cost.

I fix this issue. 
Please try to use it.

add the following in your project go.mod file.
```shell
replace github.com/rfyiamcool/go-timewheel => github.com/simonwu-os/go-timewheel v1.2.0

```
