### ISSUE TITLE
timer reset 后 旧的task 没有清理

### ISSUE THREAD

**Issue by magic000** [rfyiamcool/go-timewheel#6]

**Comment by rfyiamcool** [comment]
实在不好意思，其实在生产环境中早已修复，但社区版忘记修复。😅

[https://github.com/rfyiamcool/go-timewheel/commit/a3935e8c9b67ecfb6b2337f971dbf71601baf9a1](https://github.com/rfyiamcool/go-timewheel/commit/a3935e8c9b67ecfb6b2337f971dbf71601baf9a1)
