### ISSUE TITLE
建议AddCron增加个是否立即执行一次的可选参数

### ISSUE THREAD

**Issue by DogeVenci** [rfyiamcool/go-timewheel#9]
很多业务逻辑需要AddCron任务时候初始化先执行一次，不然要等到下次delay才能执行，自己调用一次代码又多余，
AddCron(delay time.Duration, callback func(),options ...option)  options里有个参数能设置调用AddCron时立即执行一次callback

**Comment by rfyiamcool** [comment]
to do
